apiVersion: v1
kind: Service
metadata:
  name: "${load_balancer_name}"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "${load_balancer_scheme}"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: dpm-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP