name: "order-microservice-targeted-update"

on:
  workflow_dispatch:
  workflow_call:

env:
  TF_VERSION: "1.14.1"

jobs:
  targeted_image_update:
    name: "Targeted App Deployment Update"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/order

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Terraform Init (Targeted)
        run: |
          terraform init -upgrade -reconfigure

      - name: Terraform Apply (Targeted)
        run: |
          TARGET=module.order_eks.kubectl_manifest.app_deployment
          TF_VAR_order_ssh_key_pair_value=${{ secrets.ORDER_SSH_KEY_PAIR_VALUE }}
          terraform apply -auto-approve -target=${TARGET}
